name = "landing"
title = "MongoDB Documentation"
default_domain = "landing"

[constants]
version = 4.0
package-name-org = "docs-landing"
pgp-version = "{+version+}"

# Non-snooty compatible docs are omitted
[deprecated_versions]
bi-connector = ["v1.1", "v2.0", "v2.1", "v2.2", "2.3"]
manual = ["v2.2", "v2.4", "v2.6", "v3.0", "v3.2", "v3.4"]
mms = ["v1.1", "v1.2", "v1.3"]
spark-connector = ["v1.1", "v2.0"]
